# -*- coding: utf-8 -*-
"""nettoyer_donnee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5gPR45bCw46xCEJp9HQolJe6awnQIpe
"""

import pandas as pd

donnees = pd.read_csv("festivals.csv", sep=";")
donnees.head()

import re
def departemental(x):
    try:
        if re.match(r'.*interr.egional.*',x.lower()):
            return "Interregionale"
        elif re.match(r'.*transfrontali.*',x.lower()):
            return "Transfrontalière"
        elif re.match(r'.*intercommun',x.lower()) or re.match(r".*communes.*",x.lower()):
            return "Intercommunale"
        elif re.match(r".*d.partemental.*", x.lower()):
            return "Départementale"
        elif re.match(r".*r.gional.*",x.lower()):
            return "Régionale"
        elif re.match(r"international.*", x.lower()):
            return "Internationale"
        elif re.match(r".*communale.*", x.lower()) or re.match(r".*ville.*",x.lower()) or re.match(r'.*commune.*',x.lower()) or re.match(r'.*unicipal.*',x.lower()):
            return "Communale"
        else:
            return x
    except:
        pass

envergure=donnees['Envergure territoriale']
envergure

donnees['Envergure territoriale']=donnees['Envergure territoriale'].apply(departemental)

donnees.to_csv("festivals_departements.csv", sep=";")