# -*- coding: utf-8 -*-
"""nettoyer_mails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCcY5UWOCBx9U_ZdpOzYIQD956FThG-d
"""

import pandas as pd
donnees = pd.read_csv("festivals_departements.csv", sep=";")
donnees.head()

def adressemail(x):
    listemail = str(x).split('@')
    if len(listemail) >1 :
        return x
    else :
        return "Non renseignée"


adressemail("fantinpro84@gmail.com")

donnees['Adresse e-mail']=donnees['Adresse e-mail'].apply(adressemail)

donnees.to_csv("festivals_adressemail.csv", sep=";")