# -*- coding: utf-8 -*-
"""periodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCIRF_Q4_mIvoNSm0ErTfZqK4nEoPy4R
"""

import pandas as pd
import re
donnees = pd.read_csv("festivals_sites1.csv", sep=";")
donnees.head()

def periodiser (x):
        x = str(x)
        if re.match(r".*[j,J]anvier.*", str(x)) or re.match(r".*[f,F].vrier.*", str(x)) or re.match(r".*[m,M]ars.*",str(x)) or re.match(r".*vril.*",str(x)) or re.match(r".*[m,M]ai.*", str(x)) or re.match(r"[J,j]uin", str(x)) or x=="Avant-saison (1er janvier - 20 juin)":
           return "Avant-saison (1er janvier - 20 juin)"
        elif re.match(r".*[j,J]uillet.*",str(x)) or re.match(r".*[a,A]o.t.*",str(x)) or x=="Saison (21 juin - 5 septembre)":
            return "Saison (21 juin - 5 septembre)"
        elif re.match(r"[S,s]eptembre",x) or re.match(r".*ctobre.*",str(x)) or re.match(r".*[n,N]ovembre.*",str(x)) or re.match(r".*[d,D].cembre.*", str(x)) or x=="Après-saison (6 septembre - 31 décembre)":
            return "Après-saison (6 septembre - 31 décembre)"
        elif x == "nan":
            pass
        else:
            return f"000 erreur {x}"

periodiser("Après - saison (6 septembre , 31 décembre)")

# mois = ["janvier", "février", "mars"]
# def period(x):
#      x = str(x)
#     match < <    in mois:
#         case "janvier" in x.lower()

# period("prout janvier")

donnees['Période principale de déroulement du festival']= donnees['Période principale de déroulement du festival'].apply(periodiser)
donnees['Période principale de déroulement du festival']

donnees.to_csv("festivals_periodes.csv", sep=";")