# -*- coding: utf-8 -*-
"""pings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1Bm4fGrIBtYaLoUpKNQfMWMnVLvqDIx
"""

import pandas as pd
import requests
import re
import time
donnees = pd.read_csv("festivals_adressemail.csv", sep=";")
donnees.head()

def ping(x):
    compteur =0
    try:
        if re.match(r'http.*',x):
            pass
        else:
            x = "https://"+x
        resultat= requests.get(x)
        compteur +=1
        print (f"{x} en cours, n° {compteur}")
        if resultat.status_code >= 400 :
            print(f"{x} inaccessible")
            return f"{x} (inaccessible)"
        else:
            print(f'{x} valide')
            return x
    except:
        print(f"{x} inaccessible")
        return f"{x} (inaccessible)"

ping("www.poopeegames.com/la-machine-a-coco/")

donnees['Site internet du festival']=donnees['Site internet du festival'].apply(ping)

donnees.to_csv("festivals_sites1.csv", sep=";")